### PR TITLE
Small tweaks and fixes

### LINKED ISSUE #132: Layers don't line up after document resize
Possibly related to #128. To replicate: make a new 256x256 canvas, draw something, make a new layer, draw something close/on top of what you've already drawn, resize the document to 150x150, watch pixels not lining up. Optionally, make both layers translucent and underlay a white layer to see better.
screenshot

### PR DESCRIPTION
**Pull request by Equbuxu**
Fix #132
Disable downloaded update install prompt in debug builds
Add exception logging

### CODE REVIEW

**Review by CPKreuz — APPROVED** [review]

File: PixiEditor/Models/DataHolders/Document.cs [hunk 1]
```diff
@@ -483,7 +483,7 @@ private void ResizeDocument(object[] arguments)
                 int layerHeight = (int)(Layers[i].Height * heightRatio);
 
                 Layers[i].Resize(layerWidth, layerHeight, newWidth, newHeight);
-                Layers[i].Offset = new Thickness(Layers[i].OffsetX * widthRatio, Layers[i].OffsetY * heightRatio, 0, 0);
+                Layers[i].Offset = new Thickness(Math.Floor(Layers[i].OffsetX * widthRatio), Math.Floor(Layers[i].OffsetY * heightRatio), 0, 0);
```
Comment (flabbet) [inline PixiEditor/Models/DataHolders/Document.cs:486]: What previous solution caused?

**Review by flabbet — APPROVED** [review]
